In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv("Copy of sonar data.csv", header=None)

In [3]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,51,52,53,54,55,56,57,58,59,60
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

In [4]:
df.shape

(208, 61)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       208 non-null    float64
 1   1       208 non-null    float64
 2   2       208 non-null    float64
 3   3       208 non-null    float64
 4   4       208 non-null    float64
 5   5       208 non-null    float64
 6   6       208 non-null    float64
 7   7       208 non-null    float64
 8   8       208 non-null    float64
 9   9       208 non-null    float64
 10  10      208 non-null    float64
 11  11      208 non-null    float64
 12  12      208 non-null    float64
 13  13      208 non-null    float64
 14  14      208 non-null    float64
 15  15      208 non-null    float64
 16  16      208 non-null    float64
 17  17      208 non-null    float64
 18  18      208 non-null    float64
 19  19      208 non-null    float64
 20  20      208 non-null    float64
 21  21      208 non-null    float64
 22  22      208 non-null    float64
 23  23      208 non-null    float64
 24  24      208 non-null    float64
 25  25      208 non-null    float64
 26  26      208 non-null    float64
 27  27      208 non-null    float64
 28  28      208 non-null    float64
 29  29      208 non-null    float64
 30  30      208 non-null    float64
 31  31      208 non-null    float64
 32  32      208 non-null    float64
 33  33      208 non-null    float64
 34  34      208 non-null    float64
 35  35      208 non-null    float64
 36  36      208 non-null    float64
 37  37      208 non-null    float64
 38  38      208 non-null    float64
 39  39      208 non-null    float64
 40  40      208 non-null    float64
 41  41      208 non-null    float64
 42  42      208 non-null    float64
 43  43      208 non-null    float64
 44  44      208 non-null    float64
 45  45      208 non-null    float64
 46  46      208 non-null    float64
 47  47      208 non-null    float64
 48  48      208 non-null    float64
 49  49      208 non-null    float64
 50  50      208 non-null    float64
 51  51      208 non-null    float64
 52  52      208 non-null    float64
 53  53      208 non-null    float64
 54  54      208 non-null    float64
 55  55      208 non-null    float64
 56  56      208 non-null    float64
 57  57      208 non-null    float64
 58  58      208 non-null    float64
 59  59      208 non-null    float64
 60  60      208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.2+ KB

In [6]:
df.describe()

,0,1,2,3,4,5,6,7,8,9,...,50,51,52,53,54,55,56,57,58,59
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

In [7]:
df.isnull().sum()

0     0
1     0
2     0
3     0
4     0
     ..
56    0
57    0
58    0
59    0
60    0
Length: 61, dtype: int64

In [8]:
df[60].value_counts()

M    111
R     97
Name: 60, dtype: int64

In [9]:
df.groupby(df[60]).describe()

       0                                                                 \
    count      mean       std     min      25%     50%      75%     max
60
M   111.0  0.034989  0.027074  0.0015  0.01795  0.0269  0.04185  0.1371
R    97.0  0.022498  0.014687  0.0025  0.01230  0.0201  0.02910  0.0856

       1             ...       58             59                              \
    count      mean  ...      75%     max  count      mean       std     min
60                   ...
M   111.0  0.045544  ...  0.01135  0.0364  111.0  0.006930  0.005958  0.0006
R    97.0  0.030303  ...  0.00890  0.0294   97.0  0.006024  0.003669  0.0011


       25%     50%     75%     max
60
M   0.0031  0.0053  0.0092  0.0439
R   0.0030  0.0054  0.0078  0.0180

[2 rows x 480 columns]

In [10]:
X= df.drop(columns=60, axis=1)

In [11]:
y= df[60]

In [12]:
X.shape,y.shape

((208, 60), (208,))

In [13]:
X,y

(         0       1       2       3       4       5       6       7       8   \
 0    0.0200  0.0371  0.0428  0.0207  0.0954  0.0986  0.1539  0.1601  0.3109
 1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
 2    0.0262  0.0582  0.1099  0.1083  0.0974  0.2280  0.2431  0.3771  0.5598
 3    0.0100  0.0171  0.0623  0.0205  0.0205  0.0368  0.1098  0.1276  0.0598
 4    0.0762  0.0666  0.0481  0.0394  0.0590  0.0649  0.1209  0.2467  0.3564
 ..      ...     ...     ...     ...     ...     ...     ...     ...     ...
 203  0.0187  0.0346  0.0168  0.0177  0.0393  0.1630  0.2028  0.1694  0.2328
 204  0.0323  0.0101  0.0298  0.0564  0.0760  0.0958  0.0990  0.1018  0.1030
 205  0.0522  0.0437  0.0180  0.0292  0.0351  0.1171  0.1257  0.1178  0.1258
 206  0.0303  0.0353  0.0490  0.0608  0.0167  0.1354  0.1465  0.1123  0.1945
 207  0.0260  0.0363  0.0136  0.0272  0.0214  0.0338  0.0655  0.1400  0.1843

          9   ...      50      51      52      53      54      55      56  \
 0    0.2111  ...  0.0232  0.0027  0.0065  0.0159  0.0072  0.0167  0.0180
 1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
 2    0.6194  ...  0.0033  0.0232  0.0166  0.0095  0.0180  0.0244  0.0316
 3    0.1264  ...  0.0241  0.0121  0.0036  0.0150  0.0085  0.0073  0.0050
 4    0.4459  ...  0.0156  0.0031  0.0054  0.0105  0.0110  0.0015  0.0072
 ..      ...  ...     ...     ...     ...     ...     ...     ...     ...
 203  0.2684  ...  0.0203  0.0116  0.0098  0.0199  0.0033  0.0101  0.0065
 204  0.2154  ...  0.0051  0.0061  0.0093  0.0135  0.0063  0.0063  0.0034
 205  0.2529  ...  0.0155  0.0160  0.0029  0.0051  0.0062  0.0089  0.0140
 206  0.2354  ...  0.0042  0.0086  0.0046  0.0126  0.0036  0.0035  0.0034
 207  0.2354  ...  0.0181  0.0146  0.0129  0.0047  0.0039  0.0061  0.0040

          57      58      59
 0    0.0084  0.0090  0.0032
 1    0.0049  0.0052  0.0044
 2    0.0164  0.0095  0.0078
 3    0.0044  0.0040  0.0117
 4    0.0048  0.0107  0.0094
 ..      ...     ...     ...
 203  0.0115  0.0193  0.0157
 204  0.0032  0.0062  0.0067
 205  0.0138  0.0077  0.0031
 206  0.0079  0.0036  0.0048
 207  0.0036  0.0061  0.0115

 [208 rows x 60 columns],
 0      R
 1      R
 2      R
 3      R
 4      R
       ..
 203    M
 204    M
 205    M
 206    M
 207    M
 Name: 60, Length: 208, dtype: object)

In [14]:
from sklearn.model_selection import train_test_split

In [47]:
X_train,X_test,y_train,y_test= train_test_split(X,y,test_size=.15, random_state=2,shuffle=True,
    stratify= y)

In [48]:
X_train,y_train,X_test,y_test

(         0       1       2       3       4       5       6       7       8   \
 116  0.0094  0.0333  0.0306  0.0376  0.1296  0.1795  0.1909  0.1692  0.1870
 177  0.0201  0.0165  0.0344  0.0330  0.0397  0.0443  0.0684  0.0903  0.1739
 26   0.0151  0.0320  0.0599  0.1050  0.1163  0.1734  0.1679  0.1119  0.0889
 64   0.0071  0.0103  0.0135  0.0494  0.0253  0.0806  0.0701  0.0738  0.0117
 84   0.0378  0.0318  0.0423  0.0350  0.1787  0.1635  0.0887  0.0817  0.1779
 ..      ...     ...     ...     ...     ...     ...     ...     ...     ...
 91   0.0253  0.0808  0.0507  0.0244  0.1724  0.3823  0.3729  0.3583  0.3429
 132  0.0968  0.0821  0.0629  0.0608  0.0617  0.1207  0.0944  0.4223  0.5744
 164  0.0163  0.0198  0.0202  0.0386  0.0752  0.1444  0.1487  0.1484  0.2442
 34   0.0311  0.0491  0.0692  0.0831  0.0079  0.0200  0.0981  0.1016  0.2025
 88   0.0274  0.0242  0.0621  0.0560  0.1129  0.0973  0.1823  0.1745  0.1440

          9   ...      50      51      52      53      54      55      56  \
 116  0.1725  ...  0.0216  0.0153  0.0112  0.0241  0.0164  0.0055  0.0078
 177  0.2571  ...  0.0125  0.0054  0.0057  0.0137  0.0109  0.0035  0.0056
 26   0.1205  ...  0.0086  0.0061  0.0015  0.0084  0.0128  0.0054  0.0011
 64   0.0898  ...  0.0252  0.0043  0.0048  0.0076  0.0124  0.0105  0.0054
 84   0.2053  ...  0.0093  0.0046  0.0044  0.0078  0.0102  0.0065  0.0061
 ..      ...  ...     ...     ...     ...     ...     ...     ...     ...
 91   0.2197  ...  0.0085  0.0178  0.0073  0.0079  0.0038  0.0116  0.0033
 132  0.5025  ...  0.0206  0.0073  0.0081  0.0303  0.0190  0.0212  0.0126
 164  0.2822  ...  0.0027  0.0077  0.0026  0.0031  0.0083  0.0020  0.0084
 34   0.0767  ...  0.0089  0.0087  0.0032  0.0130  0.0188  0.0101  0.0229
 88   0.1808  ...  0.0255  0.0113  0.0108  0.0085  0.0047  0.0074  0.0104

          57      58      59
 116  0.0055  0.0091  0.0067
 177  0.0105  0.0082  0.0036
 26   0.0019  0.0023  0.0062
 64   0.0032  0.0073  0.0063
 84   0.0062  0.0043  0.0053
 ..      ...     ...     ...
 91   0.0039  0.0081  0.0053
 132  0.0201  0.0210  0.0041
 164  0.0108  0.0083  0.0033
 34   0.0182  0.0046  0.0038
 88   0.0161  0.0220  0.0173

 [176 rows x 60 columns],
 116    M
 177    M
 26     R
 64     R
 84     R
       ..
 91     R
 132    M
 164    M
 34     R
 88     R
 Name: 60, Length: 176, dtype: object,
          0       1       2       3       4       5       6       7       8   \
 144  0.0299  0.0688  0.0992  0.1021  0.0800  0.0629  0.0130  0.0813  0.1761
 87   0.0856  0.0454  0.0382  0.0203  0.0385  0.0534  0.2140  0.3110  0.2837
 146  0.1021  0.0830  0.0577  0.0627  0.0635  0.1328  0.0988  0.1787  0.1199
 79   0.0108  0.0086  0.0058  0.0460  0.0752  0.0887  0.1015  0.0494  0.0472
 128  0.0374  0.0586  0.0628  0.0534  0.0255  0.1422  0.2072  0.2734  0.3070
 119  0.0261  0.0266  0.0223  0.0749  0.1364  0.1513  0.1316  0.1654  0.1864
 40   0.0068  0.0232  0.0513  0.0444  0.0249  0.0637  0.0422  0.1130  0.1911
 112  0.0454  0.0472  0.0697  0.1021  0.1397  0.1493  0.1487  0.0771  0.1171
 1    0.0453  0.0523  0.0843  0.0689  0.1183  0.2583  0.2156  0.3481  0.3337
 63   0.0067  0.0096  0.0024  0.0058  0.0197  0.0618  0.0432  0.0951  0.0836
 82   0.0409  0.0421  0.0573  0.0130  0.0183  0.1019  0.1054  0.1070  0.2302
 179  0.0394  0.0420  0.0446  0.0551  0.0597  0.1416  0.0956  0.0802  0.1618
 140  0.0412  0.1135  0.0518  0.0232  0.0646  0.1124  0.1787  0.2407  0.2682
 92   0.0260  0.0192  0.0254  0.0061  0.0352  0.0701  0.1263  0.1080  0.1523
 7    0.0519  0.0548  0.0842  0.0319  0.1158  0.0922  0.1027  0.0613  0.1465
 160  0.0258  0.0433  0.0547  0.0681  0.0784  0.1250  0.1296  0.1729  0.2794
 73   0.0139  0.0222  0.0089  0.0108  0.0215  0.0136  0.0659  0.0954  0.0786
 104  0.0307  0.0523  0.0653  0.0521  0.0611  0.0577  0.0665  0.0664  0.1460
 58   0.0225  0.0019  0.0075  0.0097  0.0445  0.0906  0.0889  0.0655  0.1624
 49   0.0119  0.0582  0.0623  0.0600  0.1397  0.1883  0.1422  0.1447  0.0487
 137  0.0430  0.0902  0.0833  0.0813  0.0165  0.0277  0.0569  0.2057  0.3887
 50   0.0353  0.0713  0.0326  0.0272  0.0370  0.0792  0.1083  0.0687  0.0298
 201  0.0335  0.0258  0.0398  0.0570  0.0529  0.1091  0.1709  0.1684  0.1865
 36   0.0094  0.0166  0.0398  0.0359  0.0681  0.0706  0.1020  0.0893  0.0381
 131  0.1150  0.1163  0.0866  0.0358  0.0232  0.1267  0.2417  0.2661  0.4346
 96   0.0181  0.0146  0.0026  0.0141  0.0421  0.0473  0.0361  0.0741  0.1398
 169  0.0130  0.0120  0.0436  0.0624  0.0428  0.0349  0.0384  0.0446  0.1318
 172  0.0180  0.0444  0.0476  0.0698  0.1615  0.0887  0.0596  0.1071  0.3175
 75   0.0202  0.0104  0.0325  0.0239  0.0807  0.1529  0.1154  0.0608  0.1317
 192  0.0056  0.0267  0.0221  0.0561  0.0936  0.1146  0.0706  0.0996  0.1673
 187  0.0368  0.0279  0.0103  0.0566  0.0759  0.0679  0.0970  0.1473  0.2164
 182  0.0095  0.0308  0.0539  0.0411  0.0613  0.1039  0.1016  0.1394  0.2592

          9   ...      50      51      52      53      54      55      56  \
 144  0.0998  ...  0.0342  0.0459  0.0277  0.0172  0.0087  0.0046  0.0203
 87   0.2751  ...  0.0128  0.0172  0.0138  0.0079  0.0037  0.0051  0.0258
 146  0.1369  ...  0.1004  0.0709  0.0317  0.0309  0.0252  0.0087  0.0177
 79   0.0393  ...  0.0161  0.0029  0.0078  0.0114  0.0083  0.0058  0.0003
 128  0.2597  ...  0.0353  0.0118  0.0063  0.0237  0.0032  0.0087  0.0124
 119  0.2013  ...  0.0135  0.0222  0.0175  0.0127  0.0022  0.0124  0.0054
 40   0.2475  ...  0.0199  0.0173  0.0163  0.0055  0.0045  0.0068  0.0041
 112  0.1675  ...  0.0137  0.0120  0.0042  0.0238  0.0129  0.0084  0.0218
 1    0.2872  ...  0.0125  0.0084  0.0089  0.0048  0.0094  0.0191  0.0140
 63   0.1180  ...  0.0029  0.0048  0.0023  0.0020  0.0040  0.0019  0.0034
 82   0.2259  ...  0.0113  0.0028  0.0036  0.0105  0.0120  0.0087  0.0061
 179  0.2558  ...  0.0118  0.0146  0.0040  0.0114  0.0032  0.0062  0.0101
 140  0.2058  ...  0.0798  0.0376  0.0143  0.0272  0.0127  0.0166  0.0095
 92   0.1630  ...  0.0132  0.0118  0.0120  0.0051  0.0070  0.0015  0.0035
 7    0.2838  ...  0.0052  0.0081  0.0120  0.0045  0.0121  0.0097  0.0085
 160  0.2954  ...  0.0121  0.0091  0.0062  0.0019  0.0045  0.0079  0.0031
 73   0.1015  ...  0.0024  0.0062  0.0072  0.0113  0.0012  0.0022  0.0025
 104  0.2792  ...  0.0063  0.0321  0.0189  0.0137  0.0277  0.0152  0.0052
 58   0.1452  ...  0.0051  0.0034  0.0129  0.0100  0.0044  0.0057  0.0030
 49   0.0864  ...  0.0069  0.0025  0.0103  0.0074  0.0123  0.0069  0.0076
 137  0.7106  ...  0.0208  0.0176  0.0197  0.0210  0.0141  0.0049  0.0027
 50   0.0880  ...  0.0098  0.0163  0.0242  0.0043  0.0202  0.0108  0.0037
 201  0.2660  ...  0.0130  0.0120  0.0039  0.0053  0.0062  0.0046  0.0045
 36   0.1328  ...  0.0134  0.0141  0.0191  0.0145  0.0065  0.0129  0.0217
 131  0.5378  ...  0.0228  0.0099  0.0065  0.0085  0.0166  0.0110  0.0190
 96   0.1045  ...  0.0076  0.0223  0.0255  0.0145  0.0233  0.0041  0.0018
 169  0.1375  ...  0.0024  0.0084  0.0100  0.0018  0.0035  0.0058  0.0011
 172  0.2918  ...  0.0122  0.0122  0.0114  0.0098  0.0027  0.0025  0.0026
 75   0.1370  ...  0.0188  0.0127  0.0081  0.0067  0.0043  0.0065  0.0049
 192  0.1859  ...  0.0185  0.0072  0.0055  0.0074  0.0068  0.0084  0.0037
 187  0.2544  ...  0.0151  0.0105  0.0024  0.0018  0.0057  0.0092  0.0009
 182  0.3745  ...  0.0357  0.0181  0.0019  0.0102  0.0133  0.0040  0.0042

          57      58      59
 144  0.0130  0.0115  0.0015
 87   0.0102  0.0037  0.0037
 146  0.0214  0.0227  0.0106
 79   0.0023  0.0026  0.0027
 128  0.0113  0.0098  0.0126
 119  0.0021  0.0028  0.0023
 40   0.0052  0.0194  0.0105
 112  0.0321  0.0154  0.0053
 1    0.0049  0.0052  0.0044
 63   0.0034  0.0051  0.0031
 82   0.0061  0.0030  0.0078
 179  0.0068  0.0053  0.0087
 140  0.0225  0.0098  0.0085
 92   0.0008  0.0044  0.0077
 7    0.0047  0.0048  0.0053
 160  0.0063  0.0048  0.0050
 73   0.0059  0.0039  0.0048
 104  0.0121  0.0124  0.0055
 58   0.0035  0.0021  0.0027
 49   0.0073  0.0030  0.0138
 137  0.0162  0.0059  0.0021
 50   0.0096  0.0093  0.0053
 201  0.0022  0.0005  0.0031
 36   0.0087  0.0077  0.0122
 131  0.0141  0.0068  0.0086
 96   0.0048  0.0089  0.0085
 169  0.0009  0.0033  0.0026
 172  0.0050  0.0073  0.0022
 75   0.0054  0.0073  0.0054
 192  0.0024  0.0034  0.0007
 187  0.0086  0.0110  0.0052
 182  0.0030  0.0031  0.0033

 [32 rows x 60 columns],
 144    M
 87     R
 146    M
 79     R
 128    M
 119    M
 40     R
 112    M
 1      R
 63     R
 82     R
 179    M
 140    M
 92     R
 7      R
 160    M
 73     R
 104    M
 58     R
 49     R
 137    M
 50     R
 201    M
 36     R
 131    M
 96     R
 169    M
 172    M
 75     R
 192    M
 187    M
 182    M
 Name: 60, dtype: object)

In [49]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [50]:
model= LogisticRegression()

In [51]:
model.fit(X_train,y_train)

LogisticRegression()

In [52]:
y_test_pred=model.predict(X_test)

In [53]:
y_train_pred = model.predict(X_train)

In [54]:
train_accuracy=accuracy_score(y_train_pred, y_train)
train_accuracy

0.8125

In [55]:
test_accuracy=accuracy_score(y_test_pred, y_test)
test_accuracy

0.90625

In [56]:
train_accuracy

0.8125

In [57]:
test_accuracy

0.90625

This is the part in which we can enter the feature/input and find the label/output

In [58]:
input_data = (0.0307,0.0523,0.0653,0.0521,0.0611,0.0577,0.0665,0.0664,0.1460,0.2792,0.3877,0.4992,0.4981,0.4972,0.5607,0.7339,0.8230,0.9173,0.9975,0.9911,0.8240,0.6498,0.5980,0.4862,0.3150,0.1543,0.0989,0.0284,0.1008,0.2636,0.2694,0.2930,0.2925,0.3998,0.3660,0.3172,0.4609,0.4374,0.1820,0.3376,0.6202,0.4448,0.1863,0.1420,0.0589,0.0576,0.0672,0.0269,0.0245,0.0190,0.0063,0.0321,0.0189,0.0137,0.0277,0.0152,0.0052,0.0121,0.0124,0.0055)

# changing the input_data to a numpy array
input_data_as_numpy_array = np.asarray(input_data)

# reshape the np array as we are predicting for one instance
input_data_reshaped = input_data_as_numpy_array.reshape(1,-1)

prediction = model.predict(input_data_reshaped)
print(prediction)

if (prediction[0]=='R'):
  print('The object is a Rock')
else:
  print('The object is a mine')

['M']
The object is a mine